[2025-03-14T07:07:51.732+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-14T07:07:51.758+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_ranking_info_update.load_data_to_redshift scheduled__2025-03-13T03:35:00+00:00 [queued]>
[2025-03-14T07:07:51.768+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_ranking_info_update.load_data_to_redshift scheduled__2025-03-13T03:35:00+00:00 [queued]>
[2025-03-14T07:07:51.768+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-03-14T07:07:51.784+0000] {taskinstance.py:2330} INFO - Executing <Task(S3ToRedshiftOperator): load_data_to_redshift> on 2025-03-13 03:35:00+00:00
[2025-03-14T07:07:51.792+0000] {standard_task_runner.py:63} INFO - Started process 26243 to run task
[2025-03-14T07:07:51.797+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'daily_ranking_info_update', 'load_data_to_redshift', 'scheduled__2025-03-13T03:35:00+00:00', '--job-id', '178', '--raw', '--subdir', 'DAGS_FOLDER/ranking_info_to_redshift.py', '--cfg-path', '/tmp/tmp7chqjgkq']
[2025-03-14T07:07:51.800+0000] {standard_task_runner.py:91} INFO - Job 178: Subtask load_data_to_redshift
[2025-03-14T07:07:51.895+0000] {task_command.py:426} INFO - Running <TaskInstance: daily_ranking_info_update.load_data_to_redshift scheduled__2025-03-13T03:35:00+00:00 [running]> on host a0d797a25898
[2025-03-14T07:07:52.047+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_ranking_info_update' AIRFLOW_CTX_TASK_ID='load_data_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2025-03-13T03:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-13T03:35:00+00:00'
[2025-03-14T07:07:52.048+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-14T07:07:52.118+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-14T07:07:52.146+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/amazon/aws/transfers/s3_to_redshift.py", line 145, in execute
    conn = S3Hook.get_connection(conn_id=self.aws_conn_id) if self.aws_conn_id else None
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `aws_default` isn't defined
[2025-03-14T07:07:52.153+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_ranking_info_update, task_id=load_data_to_redshift, run_id=scheduled__2025-03-13T03:35:00+00:00, execution_date=20250313T033500, start_date=20250314T070751, end_date=20250314T070752
[2025-03-14T07:07:52.172+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 178 for task load_data_to_redshift (The conn_id `aws_default` isn't defined; 26243)
[2025-03-14T07:07:52.217+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-03-14T07:07:52.253+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-14T07:07:52.258+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
